## Homebrew declarative setup ##

# REPOS #

tap "pol-rivero/tap"
tap "homebrew/cask-versions"

# PACKAGES #

# Power user utilities
    brew "fish"

# Development
    ## Version Control
        brew "git"
        cask "github-desktop-plus"
        brew "jj"
        brew "jjui"
    ## Language files
        ### Python
            brew "python"
        ### Rust
            brew "rust"

# Essentials
    ## Web browser

