# NOTE: This file contains configuration settings for auto-cpufreq, a CPU frequency scaling utility.
#       For more information, refer to the official documentation at https://github.com/AdnanHodzic/auto-cpufreq
# This is no longer used as TLP manages power management more comprehensively.
# This utility is mainly for CPU frequency scaling, but fails to address other power management aspects effectively.

[charger]
governor = schedutil
turbo = auto
energy_performance_preference = performance
energy_perf_bias = 6

[battery]
governor = schedutil
turbo = auto
energy_performance_preference = power
energy_perf_bias = 6

enable_thresholds = true
stop_threshold = 85
start_threshold = 84

# In the above, 'or' means what I would choose if the previous option wasn't available. The governor preference is primarily due to them being biases for the system

# https://gemini.google.com/share/125cb1ec77e4
# https://grok.com/share/bGVnYWN5_9eeba949-9674-4fb2-93d5-ebfb5dea3975
# Some inaccuracies, but fine

# While schedutil w/ guided mode is already highly efficient
# EPB = 6; Most adaptive, balances quick response with efficient idling without a bias

# I will be aliasing auto-cpufreq as "ACF"
# ACF behavior relies on its monitoring to pick the best frequencies.
# guided-autonomous (guided) mode provides better context to actual OS workloads than the standard autonomous (active) mode in the amd_pstate driver.

# PState drivers are heavily useful for scaling.
# https://docs.kernel.org/admin-guide/pm/amd-pstate.html
# amd-pstate mainly supports schedutil and ondemand for dynamic frequency control. ACF does that by itself much less comprehensively.

# The 'balanced mode' offered by ACF is fine, the rigidity of only using performance or powersave is illogical, so use schedutil.
# Search/AI results are vague. Governor changes at runtime only considers ac/battery and no real intelligent algorithm.

# Adaptive governors (schedutil/ondemand/conservative) > Static governors (performance/powersave); Usually
# Performance rarely outperforms schedutil in real world scenarios unless you are a liquid nitrogen overclocker.
# Here, performance/powersave are biases to frequency selection by ACF, but schedutil uses PELT based adjustment which is far more superior.
# Else, they are just hard locks to extreme frequencies when not using pstate drivers or ACF.
# Static governors are blind at taking frequency decisions(unless pstate set to active then powersave and performance serve as biases)

# Why schedutil > performance?
# Higher unnecessary clock speeds increase temps, causing some thermal throttling which is
# counterproductive for actual performance-heavy workloads. Scale up as per the workload demands.

# Why schedutil > powersave?
# There are factors of race to idle when required which can give some level of long term efficiency
