[main]

#### READ THIS ####
# This config file assumes that it is the default for every repo
# Many settings are pre-included here, so don't put duplicate settings in those .repo files
# Valid exceptions you can put in them are:
# gpgcheck=0
# repo_gpgcheck=0
# enabled=0

# Auto-agree
assumeno=0
assumeyes=1
defaultyes=1

# Continue w/o halting operation
# You don't need to add any of these parameters manually while you execute
# a dnf5 request to upgrade/sync/install
best=0
strict=0
allow_downgrade=1
allow_vendor_change=1
skip_if_unavailable=1

# Packages would fail to even run if this check was not present, though FEX translation might be an exception
ignorearch=0

# Cleanup unneeded packages automatically
clean_requirements_on_remove=1

# Auto prevent reinstallation of weak deps explicitly asked to be not included
exclude_from_weak_autodetect=1

# Weak deps ensure full packages are installed + better potential feature set
# Yet potential for bloat
install_weak_deps=0

# No bloating with temporary files
keepcache=0
cacheonly=0
build_cache=0

# Maybe if the user desperately needs documentation, they should see them from something like Kiwix, Distrobox or online
tsflags=nodocs

# Logging
log_compress=1
log_rotate=6
logfilelevel=0
rpmverbosity=warn
color="auto"
debug_solver=0
debuglevel=0

# Verification - transactions, file fetches, protections
gpgcheck=0
repo_gpgcheck=0
diskspacecheck=1
check_config_file_age=1

# Connectivity
max_parallel_downloads=20
throttle=0
fastestmirror=1
timeout=60

# Kernel protections disabled, we are running the bootc build in some Azure servers where buildah is running
autocheck_running_kernel=1
protect_running_kernel=0

# releasever="rawhide" unused, because most repos do not support it and ideally this should not be supported
# And infact it is not even officially valid, because even when you are on rawhide, if the current version
# of stable Fedora is 'x', rawhide builds usually report or request for 'x+1' in releasever to the repo servers
# Rawhide counterparts for the repos in the stable image is used by default inside the repo
# files directly in that rebaseable branch of this image
# We'll use the default value for releasever, provided by the upstream image

# Uncategorized
upgrade_group_objects_upgrade=1
zchunk=1
deltarpm=0
metadata_expire=8h
module_obsoletes=1
retries=8
module_stream_switch=1
multilib_policy="best"
obsoletes=1
plugins=1
